packages:
  - apps/**
  - packages/**
  - '!**/test/**'
  - '!**/node_modules/**'
  - '!**/dist/**'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - bcrypt
  - esbuild
